/* Interface copy. Project and career facts live in content.js. */
window.DESIGN_COPY = {
    pt: {
        skip: "Pular para o conteúdo",
        navWork: "Projetos", navAbout: "Sobre", navServices: "Serviços", navContact: "Vamos conversar",
        menu: "Abrir menu de navegação", menuClose: "Fechar menu de navegação",
        themeLight: "Ativar tema claro", themeDark: "Ativar tema escuro",
        availability: "Disponível para novos projetos",
        heroEyebrow: "DESENVOLVEDOR FULL STACK PLENO",
        heroLine1: "Vinicius", heroLine2: "Augusto.", heroLine3: "",
        heroDescription: "Desenvolvo sistemas, conecto serviços e automatizo o que toma tempo. Do backend à interface, com atenção a quem vai usar.",
        heroCta: "Ver projetos", heroSecondary: "Um pouco sobre mim",
        heroLocation: "Mococa, São Paulo — Brasil", heroScroll: "Um pouco do que faço",
        heroPhotoCaption: "Por trás do código, eu.", heroNow: "Atualmente na PSZ Sistemas",
        heroFocus: "BACKEND, INTERFACES & AUTOMAÇÃO",
        heroStackBackend: "Backend", heroStackInterface: "Interfaces", heroStackDelivery: "Infra & deploy",
        artLabel: "Entre ideia e código", artCaption: "Interfaces. Sistemas. Conexões.",
        workEyebrow: "01 / PROJETOS SELECIONADOS", workTitle: "Feito para funcionar.\nE para fazer sentido.",
        workDescription: "Uma seleção do meu trabalho com web, produtos digitais e sistemas. Cada projeto, um problema diferente para resolver.",
        projectsMore: "Ver todos os projetos", projectsLess: "Mostrar menos", viewProject: "Explorar projeto",
        filterAll: "Todos", filterSites: "Sites", filterSystems: "Sistemas", filterGame: "Jogos",
        aboutEyebrow: "02 / POR TRÁS DO CÓDIGO", aboutTitle: "Um pouco sobre mim.",
        aboutIntro: "Sou desenvolvedor full stack pleno, formado em Análise e Desenvolvimento de Sistemas. Moro em Mococa, no interior de São Paulo.",
        aboutText: "Trabalho com aplicações web, desktop e mobile, de operações de seguros e pagamentos a integrações com ERPs. Tenho um interesse especial por backend, automação e arquitetura — entender as regras, conectar as partes e fazer o sistema continuar evoluindo.",
        aboutNote: "Também trabalhei com suporte técnico e atendimento a clientes. Essa experiência me ajuda a olhar além do código e entender o que as pessoas precisam de verdade.",
        resume: "Baixar currículo", experienceEyebrow: "POR ONDE PASSEI", educationEyebrow: "FORMAÇÃO",
        recentEyebrow: "MAIS RECENTEMENTE", recentTitle: "O que estou construindo agora.", recentToggle: "Conhecer os projetos recentes",
        servicesEyebrow: "03 / O QUE POSSO FAZER", servicesTitle: "Seu próximo passo,\ncom uma boa base.",
        servicesDescription: "Um site do zero, um sistema sob medida ou a evolução do que já existe. Podemos começar por onde você precisa.",
        service1Title: "Sites & experiências web",
        service1Text: "Sites institucionais e landing pages com navegação clara, personalidade e cuidado em cada tamanho de tela.",
        service1Tags: "Sites · Landing pages · Responsividade",
        service2Title: "Sistemas sob medida",
        service2Text: "Aplicações, painéis e ferramentas para organizar processos. Interface, API e dados trabalhando juntos.",
        service2Tags: "Aplicações web · Dashboards · APIs",
        service3Title: "WordPress & evolução",
        service3Text: "Conteúdo fácil de atualizar e projetos que continuam melhorando. Ajustes visuais, manutenção e performance.",
        service3Tags: "WordPress · CMS · Manutenção",
        service4Title: "Integrações & automação",
        service4Text: "Conexões entre plataformas, dados e sistemas legados para reduzir tarefas manuais e simplificar a operação.",
        service4Tags: "Integrações · Automação · Legado",
        stackEyebrow: "FERRAMENTAS DO OFÍCIO", stackTitle: "A tecnologia certa\npara cada contexto.",
        contactEyebrow: "04 / VAMOS CONSTRUIR ALGO", contactLine1: "Tem uma ideia?", contactLine2: "Me conta.",
        contactDescription: "Me conte o que você tem em mente, o que precisa resolver ou o que gostaria de melhorar.",
        contactCta: "Chamar no WhatsApp", contactEmail: "Ou, se preferir, por e-mail", copyEmail: "Copiar endereço de e-mail",
        formTitle: "Um bom projeto começa com uma conversa.",
        formName: "Seu nome", formEmail: "Seu e-mail", formType: "O que você tem em mente?", formSelect: "Selecione uma opção",
        formTypeRequired: "Escolha o tipo de projeto para continuar.",
        typeSite: "Site ou landing page", typeSystem: "Sistema sob medida", typeCms: "WordPress ou CMS",
        typeMaintenance: "Manutenção e melhorias", typeIntegration: "Integração ou automação",
        formMessage: "Um pouco sobre o projeto", formSubmit: "Continuar no WhatsApp",
        formNote: "Suas respostas abrem uma conversa no WhatsApp. Você revisa a mensagem antes de enviar.",
        footerNote: "Feito com intenção, do primeiro pixel à última linha.", backTop: "Voltar ao início",
        close: "Fechar projeto", prevImage: "Imagem anterior", nextImage: "Próxima imagem",
        copied: "E-mail copiado.", copyFallback: "Abrindo seu aplicativo de e-mail.",
        externalLink: "Visitar projeto", downloadLink: "Baixar projeto", projectImage: "Imagem do projeto", imageOf: "de",
        formGreeting: "Olá, Vinicius! Gostaria de conversar sobre um projeto.",
        formNameLabel: "Nome", formEmailLabel: "E-mail", formTypeLabel: "Projeto", formMessageLabel: "Sobre a ideia",
        navigationLabel: "Navegação principal", filterProjects: "Filtrar projetos", languageLabel: "Idioma",
        whatsappGreeting: "Olá, Vinicius! Vi seu portfólio e gostaria de conversar sobre um projeto.",
        documentTitle: "Vinicius Augusto — Desenvolvedor Full Stack Pleno",
        metaDescription: "Vinicius Augusto, desenvolvedor full stack pleno em Mococa, SP. Node.js, NestJS, TypeScript e Angular. Backend, integrações, automação e projetos reais."
    },
    en: {
        skip: "Skip to content",
        navWork: "Work", navAbout: "About", navServices: "Services", navContact: "Let's talk",
        menu: "Open navigation menu", menuClose: "Close navigation menu",
        themeLight: "Switch to light theme", themeDark: "Switch to dark theme",
        availability: "Available for new projects",
        heroEyebrow: "MID-LEVEL FULL STACK DEVELOPER",
        heroLine1: "Vinicius", heroLine2: "Augusto.", heroLine3: "",
        heroDescription: "I build systems, connect services, and automate time-consuming tasks. From backend to interface, with the people who use them in mind.",
        heroCta: "View my work", heroSecondary: "A little about me",
        heroLocation: "Mococa, São Paulo — Brazil", heroScroll: "A little of what I do",
        heroPhotoCaption: "The person behind the code.", heroNow: "Currently at PSZ Sistemas",
        heroFocus: "BACKEND, INTERFACES & AUTOMATION",
        heroStackBackend: "Backend", heroStackInterface: "Interfaces", heroStackDelivery: "Infra & deployment",
        artLabel: "Between idea and code", artCaption: "Interfaces. Systems. Connections.",
        workEyebrow: "01 / SELECTED WORK", workTitle: "Built to work.\nMade to make sense.",
        workDescription: "A selection of my work across websites, digital products, and systems. Each project, a different problem to solve.",
        projectsMore: "View all projects", projectsLess: "Show less", viewProject: "Explore project",
        filterAll: "All", filterSites: "Websites", filterSystems: "Systems", filterGame: "Games",
        aboutEyebrow: "02 / BEHIND THE CODE", aboutTitle: "A little about me.",
        aboutIntro: "I'm a mid-level full stack developer with a degree in Systems Analysis and Development. I live in Mococa, in the state of São Paulo, Brazil.",
        aboutText: "I work on web, desktop, and mobile applications, from insurance and payment operations to ERP integrations. I'm especially interested in backend, automation, and architecture: understanding the rules, connecting the parts, and keeping the system easy to build on.",
        aboutNote: "I've also worked in technical support and directly with customers. That experience helps me look beyond the code and understand what people actually need.",
        resume: "Download résumé", experienceEyebrow: "WHERE I'VE WORKED", educationEyebrow: "EDUCATION",
        recentEyebrow: "RECENTLY", recentTitle: "What I'm building now.", recentToggle: "Explore recent projects",
        servicesEyebrow: "03 / WHAT I CAN DO", servicesTitle: "Your next step,\non solid ground.",
        servicesDescription: "A new website, a custom system, or improvements to what you already have. We can start where you need me.",
        service1Title: "Websites & experiences",
        service1Text: "Business websites and landing pages with clear navigation, personality, and care at every screen size.",
        service1Tags: "Websites · Landing pages · Responsive design",
        service2Title: "Custom systems",
        service2Text: "Applications, dashboards, and tools to organize everyday work. Interfaces, APIs, and data working together.",
        service2Tags: "Web applications · Dashboards · APIs",
        service3Title: "WordPress & improvements",
        service3Text: "Content that's easy to update and projects that keep getting better. Visual refinements, maintenance, and performance.",
        service3Tags: "WordPress · CMS · Maintenance",
        service4Title: "Integrations & automation",
        service4Text: "Connections between platforms, data, and legacy systems to reduce manual tasks and simplify operations.",
        service4Tags: "Integrations · Automation · Legacy systems",
        stackEyebrow: "TOOLS OF THE TRADE", stackTitle: "The right technology\nfor the context.",
        contactEyebrow: "04 / LET'S BUILD SOMETHING", contactLine1: "Have an idea?", contactLine2: "Tell me.",
        contactDescription: "Tell me what you have in mind, what needs solving, or what you'd like to improve.",
        contactCta: "Let's talk on WhatsApp", contactEmail: "Or, if you prefer, by email", copyEmail: "Copy email address",
        formTitle: "A good project starts with a conversation.",
        formName: "Your name", formEmail: "Your email", formType: "What do you have in mind?", formSelect: "Select an option",
        formTypeRequired: "Choose a project type to continue.",
        typeSite: "Website or landing page", typeSystem: "Custom system", typeCms: "WordPress or CMS",
        typeMaintenance: "Maintenance and improvements", typeIntegration: "Integration or automation",
        formMessage: "A little about the project", formSubmit: "Continue on WhatsApp",
        formNote: "Your answers open a WhatsApp conversation. You can review the message before sending it.",
        footerNote: "Made with intention, from the first pixel to the last line.", backTop: "Back to top",
        close: "Close project", prevImage: "Previous image", nextImage: "Next image",
        copied: "Email copied.", copyFallback: "Opening your email app.",
        externalLink: "Visit project", downloadLink: "Download project", projectImage: "Project image", imageOf: "of",
        formGreeting: "Hi, Vinicius! I'd like to talk about a project.",
        formNameLabel: "Name", formEmailLabel: "Email", formTypeLabel: "Project", formMessageLabel: "About the idea",
        navigationLabel: "Main navigation", filterProjects: "Filter projects", languageLabel: "Language",
        whatsappGreeting: "Hi, Vinicius! I saw your portfolio and would like to talk about a project.",
        documentTitle: "Vinicius Augusto — Mid-Level Full Stack Developer",
        metaDescription: "Vinicius Augusto, mid-level full stack developer in Mococa, Brazil. Node.js, NestJS, TypeScript, and Angular. Backend, integrations, automation, and real projects."
    }
};
